schedules:
  adhoc:
    schedule: adhoc
    notify:
      slack: cpp-driver-dev-bots
    env_vars: |
      CI_SCHEDULE=adhoc
  commit:
    schedule: per_commit
    notify:
      slack: cpp-driver-dev-bots
    branches:
      include: ["/CPP-\\d+/", "unified_driver"]
    env_vars: |
      CI_SCHEDULE=commit
  nightly:
    schedule: nightly
    notify:
      slack: cpp-driver-dev-bots
    branches:
      include: ["/CPP-\\d+/", "unified_driver"]
    matrix:
      exclude:
        - os: ['ubuntu/trusty64/cpp', 'ubuntu/xenial64/cpp', 'centos/6-64/cpp', 'centos/7-64/cpp', 'osx/high-sierra']
    env_vars: |
      CI_SCHEDULE=nightly
      CI_INTEGRATION_ENABLED=true
architecture:
  - x64
os:
  - ubuntu/bionic64/cpp
  - ubuntu/trusty64/cpp
  - ubuntu/xenial64/cpp
  - centos/6-64/cpp
  - centos/7-64/cpp
  - osx/high-sierra
env:
  LIBUV_VERSION: 1.33.0
build:
  - script: |
      . cpp-driver/.build.sh
      (
        cd cpp-driver
        configure_environment
        install_dependencies

        build_driver 'CASS'
      )

      FUNCTIONS+=($(grep -Eoh '(^cass_\s*(\w+)\s*\()|(^dse_\s*(\w+)\s*\()' cpp-driver/include/dse.h | awk -F '(' '{print $1}'));
      FUNCTIONS+=($(grep -Eoh '^cass_\s*(\w+)\s*\(' cpp-driver/include/cassandra.h | awk -F '(' '{print $1}'))
      check_driver_exports 'cpp-driver/build/libcassandra' "${FUNCTIONS[@]}"

      cpp-driver/build/cassandra-unit-tests --gtest_output=xml:unit-test-results.xml

      if [ -f cpp-driver/build/cassandra-integration-tests ]; then
        cpp-driver/build/cassandra-integration-tests --category=cassandra --keep-clusters --verbose --gtest_filter=DbaasTests* --gtest_output=xml:dbaas-integration-test-results.xml
      fi

      (
        cd cpp-driver
        install_driver
        test_installed_driver 'cassandra'
      )

  - xunit:
    - "*test-results.xml"
package:
  allow_empty: true
  include: # list of files and glob paths to include in the artifact, relative to the current working directory
    - cpp-driver/packaging/packages/*
